[package]
name = "aristech-stt-client"
description = "A Rust client library for the Aristech Speech-to-Text API"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/aristech-de/stt-clients"
keywords = [
  "speech-recognition",
  "speech-to-text",
  "real-time",
  "streaming",
  "client-library",
]
homepage = "https://github.com/aristech-de/stt-clients/blob/main/rust/README.md"
authors = ["Martin Mende"]
license = "MIT"
categories = ["api-bindings", "multimedia::audio"]

[dependencies]
tonic = { version = "0.12.3", features = ["tls", "tls-roots", "gzip"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
prost = "0.13.3"
prost-types = "0.13.3"
clap = { version = "4.1.6", features = ["derive"] }
colored = "2.0.0"
hound = "3.5.0"
cpal = "0.15.0"
inquire = { version = "0.7.5" }
regex = "1.8.1"
chrono = "0.4.31"

[dev-dependencies]
serde = { version = "1.0.152", features = ["derive"] }
dotenv = "0.15.0"

[build-dependencies]
tonic-build = "0.12.3"

[[example]]
name = "file"
path = "examples/file.rs"

[[example]]
name = "live"
path = "examples/live.rs"

[[example]]
name = "account"
path = "examples/account.rs"

[[example]]
name = "models"
path = "examples/models.rs"

[[example]]
name = "nlpFunctions"
path = "examples/nlpFunctions.rs"

[[example]]
name = "nlpProcess"
path = "examples/nlpProcess.rs"
